language: cpp
before_install:
#- sudo apt-get update
- sudo apt-get install libgtest-dev
- cd /usr/src/gtest/
- sudo cmake CMakeLists.txt
- sudo cmake -DBUILD_SHARED_LIBS=ON
- sudo make
- sudo cp *.so /usr/lib
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
#- cmake --build . --target test
- cmake --build . --target package
deploy:
 provider: script
 skip_cleanup: true
 script:
  - curl -T ipfilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uzhangnicholas:$BINTRAY_API_KEY "https://api.bintray.com/content/cnickol/Otus_cpp/hw_1_2/$TRAVIS_BUILD_NUMBER/ipfilter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

 on:
  branch: main